# Generated by Django 3.2.9 on 2021-12-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='chat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(verbose_name=''),
        ),
    ]
