# Generated by Django 3.2.9 on 2021-12-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211204_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(blank=True, null=True, to='blog.AdminField'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='blog.UserField'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users_send',
            field=models.TextField(blank=True, null=True, verbose_name='Введите через пробел участников чата'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
