# Generated by Django 3.2.9 on 2021-12-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211210_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
        migrations.DeleteModel(
            name='AdminField',
        ),
        migrations.DeleteModel(
            name='UserField',
        ),
    ]
