# Generated by Django 3.2.9 on 2022-02-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20220223_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_data_link', models.FileField(upload_to='documents/posts/%Y/%m/%d/')),
                ('document_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data_link', models.ImageField(upload_to='images/posts/%Y/%m/%d/')),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='postimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_images', to='blog.post'),
        ),
        migrations.AddField(
            model_name='postdocuments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_documents', to='blog.post'),
        ),
    ]
