# Generated by Django 3.2.9 on 2022-02-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20220225_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('news', 'News'), ('post', 'Post'), ('recom', 'Recom')], default='post', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='Группы', to='blog.StudentGroups'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('guest', 'Guest'), ('student', 'Student'), ('teacher', 'Teacher'), ('worker', 'Worker'), ('none', 'None'), ('manage', 'Manage'), ('graduate', 'Graduate')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons/'),
        ),
    ]
