# Generated by Django 3.2.9 on 2022-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20220225_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='blog.StudentGroups', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='ССылки на видео'),
        ),
    ]
