# Generated by Django 3.2.9 on 2022-03-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20220301_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
