# Generated by Django 3.2.9 on 2022-03-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20220308_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons/%owner'),
        ),
    ]
