# Generated by Django 3.2.9 on 2022-04-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20220401_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['pub_date']},
        ),
        migrations.AddField(
            model_name='comments',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reaction',
            name='target',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('news', 'News'), ('post', 'Post'), ('forum', 'Forum')], default='post', max_length=10),
        ),
    ]
