# Generated by Django 3.2.9 on 2022-04-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20220401_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
